// <auto-generated />
using Brands.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Brands.API.Migrations
{
    [DbContext(typeof(BrandsContext))]
    [Migration("20260407205804_InitialCreateBrands")]
    partial class InitialCreateBrands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Brands.API.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreatedAtYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Japon",
                            CreatedAtYear = 1937,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Estados Unidos",
                            CreatedAtYear = 1903,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Alemania",
                            CreatedAtYear = 1916,
                            Name = "BMW"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
